project:
  type: website
  pre-render:
    - publications.r
  resources:
    - _headers

website:
  title: "DI"
  description: "A data science blog and portfolio by Deden Istiawan"
  favicon: /assets/images/icon2.png
  image: /assets/images/profil-1.png
  site-url: https://dedenistiawan.netlify.app/
  repo-url: https://github.com/dedenistiawan/
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card: true
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    border: true
    left: |
      Powered by {{< iconify simple-icons:quarto >}} Quarto. 
      Base on MCU
    center: |
      &copy; []{#current-year} Deden Istiawan. [{{< iconify octicon:heart-fill-16 >}} Sponsor](https://github.com/sponsors/dedenistiawan).
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
  navbar:
    title: "DI"
    search: true
    logo: assets/images/icon2.png
    right:
      - text: About
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Projects
        href: projects.qmd
      - text: Talks
        href: talks.qmd
      - text: Publications
        href: publications.qmd
      - text: "{{< iconify fa6-brands:mastodon >}}"
        href: "https://fosstodon.org/"
        rel: me
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: "https://bsky.app/"
      - text: "{{< iconify fa6-brands:x-twitter >}}"
        href: "https://x.com/dedenistiawan"
      - text: "{{< iconify fa6-brands:linkedin >}}"
        href: 'https://www.linkedin.com/in/deden-istiawan-149806255/'
      - text: "{{< iconify octicon:mark-github-16 >}}"
        href: "https://github.com/dedenistiawan"
      - text: "{{< iconify octicon:heart-fill-16 >}}"
        href: "https://github.com/sponsors/dedenistiawan"

format:
  html:
    theme:
      - assets/stylesheets/coeos.scss
      - assets/stylesheets/projects.scss
    lang: en
    date-format: 'dddd[, the] Do [of] MMMM, YYYY'
    highlight-style: github-dark
    code-copy: true
    code-link: true
    anchor-sections: true
    email-obfuscation: javascript
    link-external-newwindow: true
    fig-align: center
    code-tools:
      source: false
      toggle: false
      caption: none
    include-after-body:
      - text: |
          <script type="text/javascript">
            const dateElements = document.querySelectorAll("p.date, div.listing-date, div.listing-file-modified");
            dateElements.forEach((el) => {
              el.innerHTML = el.innerHTML.replace(
                /(\d+)(st|nd|rd|th)/g,
                "$1<sup style='font-size:0.5em;font-style:italic;'>$2</sup>"
              );
            });
          </script>
          <script>
            document.getElementById('current-year').textContent = new Date().getFullYear();
          </script>

lightbox: auto

execute:
  freeze: true
